logs:
   loglevel: "info"
api:
   admin:
     port: 8081
   tgbot:
     port: 1234
     token: "default" 
stalcraft:
   id: "id"
   token: "default"
database:
   databaseurl: "host=postgres port=5432 dbname=telegrambot user=kek password=xxxxxxx connect_timeout=10 sslmode=disable"