services:
  crawler:
    image: ghcr.io/blacknoise228/emissiondatagostalcraftapi:latest
    command: -c --port=1234
    environment:
      - TZ=Asia/Almaty
      - STALCRAFT_ID=${STALCRAFT_ID}
      - STALCRAFT_TOKEN=${STALCRAFT_TOKEN}
      - DATABASEURL=${DATABASEURL}
    depends_on: 
      - redis
      - postgres
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia:/usr/share/zoneinfo/Asia:ro
      
  bot:
    image: ghcr.io/blacknoise228/emissiondatagostalcraftapi:latest
    command: -b --port=1234
    ports:
      - "1234:1234"
    environment:
      - TZ=Asia/Almaty
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASEURL=${DATABASEURL}
    depends_on: 
      - redis
      - postgres
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia:/usr/share/zoneinfo/Asia:ro

  adminapi:
    image: ghcr.io/blacknoise228/emissiondatagostalcraftapi:latest
    command: -a --port=8080
    environment:
      - TZ=Asia/Almaty
      - DATABASEURL=${DATABASEURL}
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia:/usr/share/zoneinfo/Asia:ro

  redis:
    image: arm64v8/redis:latest
    expose: 
      - "6379"
    restart: always

  postgres:
    image: arm64v8/postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data:    
