version: "3"

services:
  crawler:
    build: ./
    command: ./main -c --port=1234
  bot:
    build: ./
    command: ./main -b --port=1234
    ports:
    - 1234:1234
    network_mode: host
  adminapi:
    build: ./
    command: ./main -a --port=8081
    ports:
    - 8081:8081
    network_mode: host
   