services:
  crawler:
    image: ghcr.io/blacknoise228/emissiondatagostalcraftapi:latest
    command: -c --port=1234
    environment:
      - STALCRAFT_ID=${STALCRAFT_ID}
      - STALCRAFT_TOKEN=${STALCRAFT_TOKEN}
      - DATABASEURL=${DATABASEURL}
    depends_on: 
      - redis
      - postgres
    restart: always
      
  bot:
    image: ghcr.io/blacknoise228/emissiondatagostalcraftapi:latest
    command: -b --port=1234
    expose:
      - "1234"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASEURL=${DATABASEURL}
    depends_on: 
      - redis
      - postgres
    restart: always

  adminapi:
    image: ghcr.io/blacknoise228/emissiondatagostalcraftapi:latest
    command: -a --port=8080
    environment:
      - DATABASEURL=${DATABASEURL}
    ports:
      - "8080:8080"
    restart: always

  redis:
    image: redis:latest
    expose: 
      - "6379"
    restart: always

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data  
    expose:
      - "5432"
    restart: always

volumes:
  db_data:    
