definitions:
  postgres.User:
    properties:
      id:
        description: ID in the database
        type: integer
      name:
        description: UserName in telegram
        type: string
      userID:
        description: UserID in telegram
        type: integer
    type: object
info:
  contact: {}
paths:
  /emdata:
    post:
      consumes:
      - application/json
      parameters:
      - description: emData
        in: body
        name: b
        schema:
          type: string
      responses:
        "200":
          description: OK
      summary: Receives a command to start sending messages about the start of emission
  /users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/postgres.User'
      summary: Retrives all users
  /users/{id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete user based on given ID
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/postgres.User'
      summary: Retrieves user based on given ID
    post:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create new user
swagger: "2.0"
