definitions:
  jsWorker.User:
    properties:
      blocked:
        type: boolean
      id:
        type: integer
      userid:
        type: integer
      username:
        type: string
    type: object
info:
  contact:
    email: blacknoise228@gmail.com
    name: blacknoise
  description: Telegram Bot fo getting emission info from StalcraftAPI
  title: StalcraftAPI Telegram Bot
  version: 1.2.0
paths:
  /emdata:
    post:
      consumes:
      - application/json
      parameters:
      - description: emData
        in: body
        name: b
        schema:
          type: string
      responses:
        "200":
          description: OK
      summary: Receives a command to start sending messages about the start of emission
  /users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jsWorker.User'
      summary: Retrives all users
  /users/{id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete user based on given ID
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jsWorker.User'
      summary: Retrieves user based on given ID
    post:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create new user
  /users/block/{id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete user from blacklist based on given ID
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Add user to blacklist based on given ID
swagger: "2.0"
